version: '3.8'
services:
  faucet:
    restart: unless-stopped
    image: my-faucet-frontend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - REACT_APP_BACKEND_URL
        - REACT_APP_RECAPTCHA_KEY
        - STATIC_SRV_PORT
    ports:
      - ${LISTEN_ADDR}:${STATIC_SRV_PORT}
